# Generated by Django 2.1.3 on 2020-06-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dehaat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BalSheet',
            new_name='Transaction',
        ),
    ]
