# Generated by Django 2.1.3 on 2020-06-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dehaat_app', '0003_auto_20200614_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('input_file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
