# Generated by Django 2.1.3 on 2020-06-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dehaat_app', '0004_input'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='UserInput',
        ),
    ]
