# Generated by Django 2.1.3 on 2020-06-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dehaat_app', '0006_auto_20200614_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
